# This file was generated by GoReleaser. DO NOT EDIT.
cask "channel3" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "977bde1ac7a8e18926e05297f3dc682d5470d3746fb6d857a7522b1fb6572547"
      url "https://github.com/channel3-ai/cli/releases/download/v#{version}/channel3_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "1b290138ad1931c2c57defa84a334d2cd061417e8e0b0a12d3498d16786bc1ef"
      url "https://github.com/channel3-ai/cli/releases/download/v#{version}/channel3_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "949a252bca31bbbf3366d7a2391c41ebfccbf8fe4a0f76c6542e53089e6d5113"
      url "https://github.com/channel3-ai/cli/releases/download/v#{version}/channel3_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea20cf8420a7c4119b8a1e4274018757c6d466951cd1a826737ea076c8d5a397"
      url "https://github.com/channel3-ai/cli/releases/download/v#{version}/channel3_#{version}_linux_arm64.tar.gz"
    end
  end

  name "channel3"
  desc "The official CLI of Channel3"
  homepage "https://docs.trychannel3.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "channel3"
  manpage "man/man1/channel3.1.gz"
  bash_completion "completions/channel3.bash"
  fish_completion "completions/channel3.fish"
  zsh_completion "completions/channel3.zsh"

  # No zap stanza required

end
