# Originally generated by GoReleaser from channel3-ai/cli, which is retired.
# Nothing regenerates this file any more, so it is now hand-maintained.
#
# The CLI moved to npm at 0.5.0: `npm install -g @channel3/cli`. That build is
# Rust, generated by Fern, and ships prebuilt binaries per platform. This cask
# still installs the last Go build (0.4.0) and will never be updated.
cask "channel3" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "6a62a3cec68f78c2d7cf86541c7a183bde5ca503b904f578a6d99f0737e1670f"
      url "https://github.com/channel3-ai/cli/releases/download/v#{version}/channel3_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "2a05c0e552427bbcaff017db6d617483b99cb3765177a7f8c23affe3da521839"
      url "https://github.com/channel3-ai/cli/releases/download/v#{version}/channel3_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "5fecb2e1debc83d70974d19832a15f59f706205b260a5e413e8cba6266673f01"
      url "https://github.com/channel3-ai/cli/releases/download/v#{version}/channel3_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2e65eba2270a586b641055049b6f1502ded7d2c0a76d398df880f3ca5a8c06bf"
      url "https://github.com/channel3-ai/cli/releases/download/v#{version}/channel3_#{version}_linux_arm64.tar.gz"
    end
  end

  name "channel3"
  desc "The official CLI of Channel3"
  homepage "https://docs.trychannel3.com"

  # Frozen at the final Go release. `brew upgrade` would otherwise leave people
  # on 0.4.0 indefinitely with no indication that the CLI had moved.
  deprecate! date: "2026-08-18", because: "has been replaced by the npm package @channel3/cli. Run `brew uninstall --cask channel3 && npm install -g @channel3/cli`. Note that `--query` is now `--query-param` for search terms"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "channel3"
  manpage "man/man1/channel3.1.gz"
  bash_completion "completions/channel3.bash"
  fish_completion "completions/channel3.fish"
  zsh_completion "completions/channel3.zsh"

  # No zap stanza required

end
